GET http://localhost:8000/api/users

###
GET http://localhost:8000/api/users/2


###
PUT http://localhost:8000/api/users/6
Content-Type: application/json

{
    "name": "leroy",
    "contact_phone": "12345666",
    "phone_verified": true,
    "email": "lee@gmail.com",
    "email_verified": true,
    "confirmation_code": "223",
    "password": "2222"
}

###
DELETE  http://localhost:8000/api/users/13



///state
###
GET http://localhost:8000/api/state

###
DELETE http://localhost:8000/api/state/15

###

GET http://localhost:8000/api/state/15

###
//update
POST  http://localhost:8000/api/users
Content-Type: application/json

{
  "name": "YUNO",
    "contact_phone": "182828373",
    "phone_verified": true,
    "email": "YUNO@gmail.com",
    "email_verified": true,
    "confirmation_code": "2030",
    "password": "1234"
  }


###





//state
###
GET http://localhost:8000/api/state

###

PUT http://localhost:8000/api/state/13
Content-Type: application/json

{
   
   "name": "kutus",
   "code" : "Kg"


}
###

POST http://localHost/api/state
Content-Type: application/json

{
   "name": "maina",
   "code": "mn"

}

###
DELETE http://localhost:8000/api/state/2



//city
###
GET http://localhost:8000/api/cities/8
###
DELETE http://localhost:8000/api/cities/6

###
 GET http://localhost:8000/api/cities

###
 POST http://localhost:8000/api/cities
Content-Type: application/json

{
   "name": "maina",
    "state_id" : 1

}

###
POST http://localhost:8000/api/cities
Content-Type: application/json

{
   "name": "maina",
    "state_id" : 1

}



//ADDRESSES
###
GET http://localhost:8000/api/address

### //by id

GET http://localhost:8000/api/address/2

### //creating
POST http://localhost:8000/api/address
Content-Type: application/json

{
   "id" : 2,
   "street_address_1": "456 Elm St",
  "street_address_2": "Apt 2",
  "zip_code": "23456",
  "delivery_instructions": "Leave at the back door",
  "user_id": 2,
  "city_id": 2
}


### ///delete
DELETE http://localhost:8000/api/address/2



